- helm/thingsboard/Chart.yaml
- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/values.yaml
I am deploying thingsboard into a kind cluster running locally in my laptop and the initialize database job takes a lot of time to complete just because checking the status of the database takes more than 3 seconds.
Being able to set up this timeout using values helped me to finally start the chart without further issues. I set up the default value for the timeout in the values to be backward compatible.
find out more details at: https://www.postgresql.org/docs/current/app-pg-isready.html#:~:text=The%20default%20is%203%20seconds.
This PR was created into thingsboard repository too but there is no feedback from them for this small change.
> timeout for database initialization job configurable by helm values file

- helm/README.md
- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/values.yaml
The Helm chart of TBu always installs the database. Therefore we are not being able to upgrade the database after the first install. 
Some parameters are added into the helm chart in order to setup the install of upgrade behavior.
> EVP-2115. initialization job can install or update the database

- helm/thingsboard/templates/node.yaml
- helm/thingsboard/values.yaml
I manually generated yaml with and without configmap:
```
helm template evp ./helm/thingsboard/ -s templates/node.yaml  --set node.ruleChain.configmapName="" > without.yaml 
```
```
helm template evp ./helm/thingsboard/ -s templates/node.yaml  --set node.ruleChain.configmapName="some-config" > with.yaml 
```
```
$ diff without.yaml with.yaml 
97a98,100
>             - mountPath: /usr/share/thingsboard/data/json/tenant/rule_chains/root_rule_chain.json
>               subPath: root_rule_chain.json
>               name: some-config
120a124,129
>         - name: some-config
>           configMap:
>             name: some-config
>             items:
>             - key: rule_chain
>               path: root_rule_chain.json
```
> [EVP-2054] Add configuration to overwrite default root chain.

- helm/README.md
- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/values.yaml
Relates to https://midokura.atlassian.net/browse/EVP-2115 and https://midokura.atlassian.net/browse/EVP-2027
Database upgrades can be skipped if initDBJob.fromVersion parameter is not set. 
Notice that 'helm upgrade' command could be executed at any time without triggering any migration to the database.
> EVP-2115 - Database upgrades can be skipped 

- helm/thingsboard/templates/node.yaml
- helm/thingsboard/values.yaml
So we can mitigate a possible bug in [TB rest client](https://github.com/thingsboard/thingsboard/issues/8038)
[JIRA](https://midokura.atlassian.net/browse/EVP-1800)
Deployed evp2 using this TB helm chart as dependency, checked default values. Then set token expiration time to 2 seconds, restart evp-api pods and verified that Iot ping threads deadlocked after 5 token refreshes:
```
TP GET http://evp2-node:8080/api/dashboard/serverTime","context":"default"}
{"timestamp":"2023-02-06T20:53:25.002Z","level":"DEBUG","thread":"iot-ping-thread","logger":"org.springframework.web.client.RestTemplate","message":"Accept=[application/json, application/*+json]","context":"default"}
{"timestamp":"2023-02-06T20:53:25.009Z","level":"DEBUG","thread":"iot-ping-thread","logger":"org.springframework.web.client …
```
> [EVP-1800] Parametrize token expiration time.

- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/values.yaml
Equal to: https://github.com/midokura/evp-chart/pull/235
The Job can't be scheduled on a multi-node K8s cluster because the user can't define the nodeSelector, affinity, and tolerations.
> added: nodeSelector, tolerations and affinity to initDBJon

- helm/thingsboard/templates/node-configmap.yaml
- helm/thingsboard/templates/transport-configmap.yaml
`UseContainerSupport` is set to allow the JVM to be aware of the container resource limits. This should be enabled by default, but was added for visibility.
`MaxRAMPercentage` overrides the default used, which should be 75%, but in the EVP2 perf cluster it was only 25%, so that we allow TB node to handle more devices (>1000).
> fix(node): Increase the available memory to TB node

- helm/thingsboard/templates/node.yaml
When a tb node starts it register to zookeeper with a service info that contains this TB_SERVICE_ID. When all the pods have the same id, they all share the same partitions, leaving the rest to no one.
> fix(partition): set the service id as the pod id

- helm/thingsboard/templates/component-service.yaml
- helm/thingsboard/values.yaml
The MQTT endpoint is exposed via a service object attached to a
load balancer in the cloud provider. If we want to allowlist this
service we need to specify the ranges using the
`loadBalancerSourceRanges` property of the Service. For AKS, this
is documented [here].
[here]: https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#restrict-inbound-traffic-to-specific-ip-ranges
EVP-2746
<details>
<summary>
Committer details
</summary>
Local-Branch: master
</details>
> feat(mqtt): enable allowlisting for mqtt endpoint

- helm/thingsboard/templates/node.yaml
JIRA: https://midokura.atlassian.net/browse/EVP-2756
The issue in my local deployment:
```
NAME                                              READY   STATUS    RESTARTS        AGE
evp-api-84c65c4c5-9rfn4                           1/1     Running   1 (2m20s ago)   5m54s
evp-env-cert-manager-5d5949cf8b-zzxpm             1/1     Running   0               27m
evp-env-cert-manager-cainjector-656b55895-qt7ws   1/1     Running   0               27m
evp-env-cert-manager-webhook-c5ff45ff6-m22sb      1/1     Running   0               27m
evp-env-controller-5965f74989-lgsjc               1/1     Running   0               27m
evp-init-tb-db-3-dfn8g                            1/1     Running   0               4m49s
evp-jsexecutor-db6b957bc-bncsw                    1/1     Running   0               24m …
```
> fix(tb-node): Increase timeout for readiness probe.

- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/templates/js-executor.yaml
- helm/thingsboard/templates/node-db-configmap.yaml
- helm/thingsboard/templates/node.yaml
- helm/thingsboard/values.yaml
new version of postgres doesn't have the same fields.
Tested locally:
```
(⎈|kind-kind:default)
$ salmendros@salmendros [12:30:42] [~/midokura/dev/python_projects/evp-dev-tools/evp-cli] [main *]
-> % k get po
NAME                                              READY   STATUS    RESTARTS        AGE
evp-api-5f9dfd489c-52c97                          1/1     Running   0               13m
evp-env-cert-manager-5d5949cf8b-lslq9             1/1     Running   0               15m
evp-env-cert-manager-cainjector-656b55895-grfc2   1/1     Running   0               15m
evp-env-cert-manager-webhook-c5ff45ff6-6qf9h      1/1     Running   0               15m
evp-env-controller-5965f74989-hzzqt               1/1     Running   0               15m
evp-jsexecutor-6fd7f4c745-jkbr8                   1/1 …
```
> fix(helm): fix postgres fields

- helm/thingsboard/Chart.yaml
- helm/thingsboard/templates/initializedb-job.yaml
- helm/thingsboard/templates/js-executor.yaml
- helm/thingsboard/templates/node-db-configmap.yaml
- helm/thingsboard/templates/node.yaml
- helm/thingsboard/values.yaml
This reverts commits 75cf58a1ea0a0afe88a98aa7228757eec428f6b5 and 76fbb3ed0f63e44d35437bb38447f5607700e56d.
Upgrading the `postgresql-ha` HELM chart fails in demo and performance environments, due to the changes to the statefulset that requires it to be recreated.
Error example from installing the `evp` HELM chart:
```
Upgrade "evp" failed: cannot patch "evp-postgresql" with kind StatefulSet: StatefulSet.apps "evp-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden && cannot patch "evp-tb-postgresql" with kind StatefulSet: StatefulSet.apps "evp-tb-postgresql" is invalid: spec: Forbidden: updates to statefulset spec for fields other …
```
> revert: bump to postgresql-ha 11.8.1

- helm/thingsboard/templates/node.yaml
- helm/thingsboard/values.yaml
EVP1 was not setting per device inactivity timeout (so it was using a default of 10 minutes). In EVP2 though, we use a per device inactivity timeout of 1 minute.
To avoid having to deal with per device inactivity timeout during migration from EVP1 to EVP2, we set a global default of 1 minute so if we don't set the per device inactivity, we'll default to the right timeout.
References:
[code](https://github.com/thingsboard/thingsboard/blob/e4bf5a9b3a5134c20df3c014da170cbf9fa687c2/application/src/main/resources/thingsboard.yml#L660) [docs](https://thingsboard.io/docs/user-guide/device-connectivity-status/)
> Align default inactivity timeout with EVP configuration

- helm/thingsboard/templates/component-service.yaml
- helm/thingsboard/values.yaml
By default & by design, ClusteIP k8s Service does set nodePort in the Service object spec when created, to a random value within some cluster-specific range. This change allows specifiying an explicit nodePort value.
The feature is disabled by default.
See [related PR](https://github.com/midokura/evp-dev-tools/pull/480#discussion_r1351684571) for more details why this is needed.
> feat(mqtt): support explicit service nodePort

- helm/thingsboard/Chart.yaml
- helm/thingsboard/templates/_helpers_midokura.tpl
- helm/thingsboard/templates/coap-transport.yaml
- helm/thingsboard/templates/http-transport.yaml
- helm/thingsboard/templates/mqtt-transport.yaml
- helm/thingsboard/templates/node.yaml
This will allow easier and better setup of affinity on Thingsboard services, using same conventions as in Bitnami charts.
Related to: https://midokura.atlassian.net/browse/EVP-2685
> feature(ha): Use Bitnami Common affinity templates

- .github/workflows/release.yml
Bumping to v1.5.0.
Mostly to check if it can handle by default OCI repos (to avoid problems like https://github.com/midokura/thingsboard-ce-k8s/actions/runs/6483652142/job/17605731743#step:5:36).
OCI repos are the default in some cases (like Bitnami, see this [Bitnami blog entry](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html))
> chore(ci): bump chart-releaser-action to v1.5.0

- helm/thingsboard/templates/node-db-configmap.yaml
- helm/thingsboard/values.yaml
- Currently, SQL ttl settings are set manually by editing the configmap after building evp-hub.
- Manual settings will require more effort, so you need to change it so that you can build an evp-hub that includes sql ttl settings.
- In the future, we will build evp-hub with values.yaml that describes SQL ttl settings.
> add(ttl): Added SQL ttl settings

- helm/thingsboard/templates/node-db-configmap.yaml
- helm/thingsboard/values.yaml
The values for 'value' and 'execution_interval' were swapped, which made ThingsBoard fail to deploy for two reasons:
- First, a recurring Helm issue converts long integers to scientific notation, and ThingsBoard failed to load a big SQL_TTL_TS_TS_KEY_VALUE_TTL as a long. With the correct values this will no longer be an issue, but I have ensured that they are not converted to scientific annotation anyway, in case someone ever tries to use a big integer there. I have fixed it the same way it was done here: https://github.com/midokura/evp-chart/pull/339.
- Second, ThingsBoard just does not work with an SQL_TTL_TS_EXECUTION_INTERVAL of 0, but that is fixed using the correct default
I have also change the default value of sql.ts.ttl.enabled, as it's true in ThingsBoard's code: …
> fix(config): fix commit f2922f4

- helm/thingsboard/templates/mqtt-transport.yaml
- helm/thingsboard/templates/node.yaml
- helm/thingsboard/templates/web-ui.yaml
We noticed that the tags on container template is needed in order to
receive Thingsboard telemetry, beyond the tags on Deployment
> Set datadog tags on container template too

- helm/thingsboard/templates/mqtt-transport.yaml
- helm/thingsboard/templates/node.yaml
- helm/thingsboard/templates/web-ui.yaml
We want the database to be called 'thingsboard-postgres' and map with
current monitors.
Replace 'appVersion' with 'AppVersion' [1]
[1]: https://stackoverflow.com/questions/69817305/how-set-field-app-version-in-helm3-chart
> Add service mappings to thingsboard

- helm/thingsboard/templates/js-executor.yaml
・The js-excuter node selector is supported, but it is incorrect and the js-excuter Pod cannot be placed on a specific node.
・If a Pod cannot be placed on a specific node, it may affect the resources of that node if it is placed on another node, so I would like to fix this.
　Change the description of "jexecutorSelector" in js-excuter to "nodeSelector"
> fix(jsexecutor): fix jexecutorSelector to nodeSelector

- helm/thingsboard/templates/mqtt-transport.yaml
- helm/thingsboard/templates/node.yaml
- helm/thingsboard/templates/web-ui.yaml
Pin version to latest available [`v1.45.2`](https://github.com/DataDog/dd-trace-java/releases/tag/v1.45.2)
> Pin DD dd-trace-java version to v1.45.2

- helm/thingsboard/templates/evp-mqtt-transport-featureflags-configmap.yaml
- helm/thingsboard/templates/evp-mqtt-transport.yaml
This change adds an optional `evp-mqtt-config.yaml` that contains the feature flag configuration for all the current and future changes that will be added to the MQTT broker in the effort to remove ThingsBoard.
The purpose of adding these early is to create CI pipelines that can enable them for current and future EVP e2e tests.
The change will only be visible if `evp.mqtt.enabled` is `true`, so these features are not accessible in environments until we are ready to expose them.
The feature flags are not mentioned in the `values.yaml` to avoid confusion in the majority of deployments -  since they are not needed/wanted. They can be added once they are ready for deployment.
JIRA: https://aitrios.atlassian.net/browse/CTRL-4476
> Add EVP feature flags in an optional ConfigMap

- helm/thingsboard/Chart.yaml
- helm/thingsboard/values.yaml
Upgrade the version of the chart from 15.3.4 to 19.1.5, which supports
a "new" `service.headless.publishNotReadyAddresses` that should allow
Kafka pods start synchronizing each other and being published in the
service before the readiness probe is successful.
At the same time, pin kafka and zookeeper image tags to the one we are using
right now.
According to [upgrade docs], it should only affect the Zookeeper
version, and we shouldn't experience any error on the configuration
values we use right now.
I did a small upgrade test in a separate cluster and it worked
successfully, so hopefully the new Zookeeper version will not affect
our cluster. Unfortunately, I think we cannot tell exactly until we
run all the PDCs in SIE env.
Implements: https://aitrios.atlassian.net/browse/REL-3715 …
> Upgrade kafka chart version

- helm/thingsboard/templates/transport-configmap.yaml
This PR configures the evp-mqtt component for logging in json format independently of the global.jsonLogs parameter that is used in other components and cannot be enabled.
Change-Id: Ib65015c0f4ace5436fe1928bd7106ac85eaf374b
> evp-mqtt logs in json format
